// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientFollowUp.Api.Data;

#nullable disable

namespace PatientFollowUp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518023359_AddDemoSeedData")]
    partial class AddDemoSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("PatientFollowUp.Api.Models.AuditEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Created",
                            Details = "Initial demo follow-up task created during database seeding.",
                            EntityId = 1,
                            EntityType = "FollowUpTask",
                            Timestamp = new DateTime(2026, 5, 10, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Action = "Created",
                            Details = "Initial demo follow-up task created during database seeding.",
                            EntityId = 2,
                            EntityType = "FollowUpTask",
                            Timestamp = new DateTime(2026, 5, 11, 15, 30, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PatientFollowUp.Api.Models.FollowUpTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientReferenceCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FollowUpTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Review demonstration lab follow-up task.",
                            DueDate = new DateOnly(2026, 5, 15),
                            PatientReferenceCode = "DEMO-001",
                            Status = 0,
                            TaskType = 0,
                            UpdatedAt = new DateTime(2026, 5, 10, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 11, 15, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Send demonstration appointment reminder.",
                            DueDate = new DateOnly(2026, 5, 20),
                            PatientReferenceCode = "DEMO-002",
                            Status = 1,
                            TaskType = 1,
                            UpdatedAt = new DateTime(2026, 5, 12, 16, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
